name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정(00:00)에 실행
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run update_tistory_visitor.py
        run: |
          python update_tistory_visitor.py

      - name: Commit and push changes
        run: |
          git config --global user.name '박도연'
          git config --global user.email 'ehduszkdzkd@naver.com'
          git add README.md
          # 변경 사항 없으면 커밋 생략하고 종료
          git diff --quiet && echo "No changes to commit" && exit 0
          git commit -m 'Update README with latest visitor count'
          git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.DOYEON_KEY}}
